function isoFrom(now, offsetHours) {
  return new Date(now.getTime() + (offsetHours * 60 * 60 * 1000)).toISOString();
}

function makeSource(id, name, sourceUrl, retrievedAt) {
  return {
    sourceId: id,
    sourceName: name,
    sourceType: 'official',
    sourceUrl,
    retrievedAt,
  };
}

function snapshotIdFrom(date) {
  const compact = date.toISOString().slice(0, 19).replace(/[-:]/g, '').replace('T', 't');
  return `mr-${compact}z`;
}

export function createPreviewSnapshot(now = new Date()) {
  const generatedAt = isoFrom(now, 0);
  const observedAt = isoFrom(now, -15);
  const retrievedAt = isoFrom(now, -1);
  const validUntil = isoFrom(now, 6.5);
  const treasury = makeSource(
    'us-treasury-rates',
    'U.S. Department of the Treasury',
    'https://home.treasury.gov/resource-center/data-chart-center/interest-rates',
    retrievedAt,
  );
  const fred = makeSource(
    'federal-reserve-broad-dollar',
    'Federal Reserve Bank of St. Louis',
    'https://fred.stlouisfed.org/series/DTWEXBGS',
    retrievedAt,
  );
  const cbrt = makeSource(
    'cbrt-usd-try',
    'Central Bank of the Republic of Türkiye',
    'https://www.tcmb.gov.tr/',
    retrievedAt,
  );
  const indicator = (id, label, displayValue, unit, change, macroSignal, source, tags) => ({
    id,
    label,
    rawValue: Number.parseFloat(displayValue),
    displayValue,
    unit,
    change: { rawValue: 0, displayValue: change, period: 'previous-observation', direction: 'flat' },
    observedAt,
    retrievedAt,
    freshness: { status: 'fresh', ageSeconds: 3600, maxAgeSeconds: 172800 },
    macroSignal,
    source,
    marketTags: tags,
  });

  return {
    schemaVersion: 1,
    id: snapshotIdFrom(now),
    generatedAt,
    validUntil,
    pipeline: {
      runId: 'run-design-preview',
      status: 'healthy',
      startedAt: isoFrom(now, -0.5),
      completedAt: generatedAt,
      coverage: {
        expectedSources: 9,
        successfulSources: 7,
        staleSources: 1,
        failedSources: 1,
        marketTags: ['global', 'united-states', 'turkey', 'rates', 'fx'],
      },
      publicNote: 'Local interface preview. All displayed values are illustrative.',
    },
    macroConditions: {
      score: 55,
      label: 'balanced',
      summary: 'Rate levels keep conditions firm while a positively sloped U.S. curve offsets part of the pressure. The Turkey-specific currency input remains isolated from the global readout.',
      scoreScale: {
        minimum: 0,
        maximum: 100,
        higherMeans: 'More restrictive macro-financial conditions',
      },
      methodology: {
        id: 'macro-conditions-v1',
        version: '1.0.0',
        description: 'Deterministic weighted score built only from published macro indicators.',
        baselineScore: 50,
        formula: 'score = clamp(baselineScore + sum(driver contributionPoints), 0, 100)',
      },
      drivers: [
        {
          indicatorId: 'us-treasury-2y',
          label: 'U.S. Treasury 2Y',
          weight: 0.25,
          normalizedSignal: 0.4,
          contributionPoints: 4,
          direction: 'restrictive',
          explanation: 'The two-year yield remains above the method’s neutral band, keeping near-term rate conditions firm.',
          marketTags: ['global', 'united-states', 'rates'],
        },
        {
          indicatorId: 'us-treasury-10y',
          label: 'U.S. Treasury 10Y',
          weight: 0.25,
          normalizedSignal: 0.5,
          contributionPoints: 5,
          direction: 'restrictive',
          explanation: 'The ten-year yield raises the long-duration cost of capital in the illustrative readout.',
          marketTags: ['global', 'united-states', 'rates'],
        },
        {
          indicatorId: 'us-curve-2s10s',
          label: 'U.S. 2Y–10Y curve',
          weight: 0.2,
          normalizedSignal: -0.2,
          contributionPoints: -2,
          direction: 'supportive',
          explanation: 'A positive curve slope offsets part of the pressure from outright Treasury yield levels.',
          marketTags: ['global', 'united-states', 'rates'],
        },
        {
          indicatorId: 'fed-broad-usd',
          label: 'Broad U.S. dollar',
          weight: 0.2,
          normalizedSignal: 0.3,
          contributionPoints: 3,
          direction: 'restrictive',
          explanation: 'A firm broad-dollar input tightens conditions for dollar-sensitive borrowers and trade.',
          marketTags: ['global', 'united-states', 'fx'],
        },
        {
          indicatorId: 'cbrt-usd-try',
          label: 'CBRT USD/TRY',
          weight: 0.1,
          normalizedSignal: 0.1,
          contributionPoints: 1,
          direction: 'restrictive',
          explanation: 'The currency input adds a small Türkiye-specific contribution without changing the global signal.',
          marketTags: ['turkey', 'fx'],
        },
      ],
    },
    indicators: [
      indicator('us-treasury-2y', 'U.S. Treasury 2Y', '4.25%', 'percent', '-3 bp', 'tightening', treasury, ['global', 'united-states', 'rates']),
      indicator('us-treasury-10y', 'U.S. Treasury 10Y', '4.50%', 'percent', '-2 bp', 'tightening', treasury, ['global', 'united-states', 'rates']),
      indicator('us-curve-2s10s', 'U.S. 2Y–10Y curve', '+25 bp', 'basis-points', '+1 bp', 'easing', treasury, ['global', 'united-states', 'rates']),
      indicator('fed-broad-usd', 'Broad U.S. dollar', '110.40', 'index', '+0.20', 'tightening', fred, ['global', 'united-states', 'fx']),
      indicator('cbrt-usd-try', 'CBRT USD/TRY', '35.5000', 'currency-rate', '+0.0800', 'tightening', cbrt, ['turkey', 'fx']),
    ],
    priorityDevelopments: [
      {
        id: 'development-us-curve',
        headline: 'The U.S. curve remains positively sloped in the preview readout',
        summary: 'The illustrative ten-year yield is 25 basis points above the two-year yield, partially offsetting pressure from high outright rates.',
        impact: 'medium',
        firstSeenAt: retrievedAt,
        updatedAt: retrievedAt,
        provenance: [treasury],
        marketTags: ['global', 'united-states', 'rates'],
      },
      {
        id: 'development-turkey-fx',
        headline: 'The Türkiye-specific currency input moved higher',
        summary: 'The illustrative daily move is directionally restrictive but remains isolated from the global macro score narrative.',
        impact: 'medium',
        firstSeenAt: retrievedAt,
        updatedAt: retrievedAt,
        provenance: [cbrt],
        marketTags: ['turkey', 'fx'],
      },
    ],
    stories: [
      {
        id: 'story-us-yield-curve',
        headline: 'Official Treasury observations show a positive preview 2Y–10Y slope',
        summary: 'The design fixture places the two-year yield at 4.25% and the ten-year yield at 4.50%.',
        whyItMatters: 'Separating the slope from outright yield levels makes the score’s offsetting forces visible.',
        url: treasury.sourceUrl,
        publisher: treasury.sourceName,
        publishedAt: observedAt,
        retrievedAt,
        impact: 'medium',
        category: 'rates',
        provenance: [treasury],
        marketTags: ['global', 'united-states', 'rates'],
      },
      {
        id: 'story-broad-dollar',
        headline: 'The broad-dollar measure is firm in the illustrative snapshot',
        summary: 'The preview index is 110.40, up 0.20 from its previous observation.',
        whyItMatters: 'Dollar strength is traced separately because it can tighten financing and trade conditions outside the United States.',
        url: fred.sourceUrl,
        publisher: fred.sourceName,
        publishedAt: isoFrom(now, -16),
        retrievedAt,
        impact: 'medium',
        category: 'fx',
        provenance: [fred],
        marketTags: ['global', 'united-states', 'fx'],
      },
      {
        id: 'story-cbrt-usdtry',
        headline: 'CBRT supplies the preview USD/TRY observation',
        summary: 'The illustrative currency rate is tagged only for Türkiye and foreign exchange.',
        whyItMatters: 'A local currency move is not mislabeled as a global market regime signal.',
        url: cbrt.sourceUrl,
        publisher: cbrt.sourceName,
        publishedAt: isoFrom(now, -2),
        retrievedAt,
        impact: 'medium',
        category: 'fx',
        provenance: [cbrt],
        marketTags: ['turkey', 'fx'],
      },
    ],
    calendar: [
      {
        id: 'calendar-us-release-preview',
        title: 'U.S. macro release window',
        countryCode: 'US',
        scheduledAt: isoFrom(now, 2),
        timezone: 'America/New_York',
        status: 'scheduled',
        impact: 'high',
        previous: 'Illustrative',
        forecast: null,
        actual: null,
        unit: 'preview',
        referencePeriod: 'Design fixture',
        marketTags: ['global', 'united-states', 'inflation'],
        source: treasury,
      },
      {
        id: 'calendar-cbrt-preview',
        title: 'CBRT policy communication window',
        countryCode: 'TR',
        scheduledAt: isoFrom(now, 28),
        timezone: 'Europe/Istanbul',
        status: 'scheduled',
        impact: 'high',
        previous: null,
        forecast: null,
        actual: null,
        unit: 'preview',
        marketTags: ['turkey', 'rates', 'central-banks'],
        source: cbrt,
      },
    ],
    digest: {
      id: 'digest-design-preview',
      periodStart: isoFrom(now, -24),
      periodEnd: generatedAt,
      generatedAt,
      title: 'Illustrative engine readout',
      summary: 'Design preview only.',
      highlights: [
        {
          id: 'highlight-us-rates',
          text: 'The two Treasury rate levels add nine points to the deterministic preview score.',
          impact: 'high',
          relatedStoryIds: ['story-us-yield-curve'],
        },
        {
          id: 'highlight-curve',
          text: 'The positively sloped curve offsets two points of restrictive pressure.',
          impact: 'medium',
          relatedStoryIds: ['story-us-yield-curve'],
        },
        {
          id: 'highlight-turkey-fx',
          text: 'USD/TRY adds one point only to the Türkiye-tagged view.',
          impact: 'medium',
          relatedStoryIds: ['story-cbrt-usdtry'],
        },
      ],
      storyIds: ['story-us-yield-curve', 'story-broad-dollar', 'story-cbrt-usdtry'],
      itemCount: 3,
      marketTags: ['global', 'united-states', 'turkey', 'rates', 'fx'],
    },
    sources: [
      {
        id: 'us-treasury-rates',
        name: treasury.sourceName,
        type: 'official',
        url: treasury.sourceUrl,
        status: 'healthy',
        lastAttemptAt: retrievedAt,
        lastSuccessAt: retrievedAt,
        itemsUsed: 3,
        marketTags: ['global', 'united-states', 'rates'],
        publicMessage: 'Latest preview retrieval succeeded.',
      },
      {
        id: 'federal-reserve-broad-dollar',
        name: fred.sourceName,
        type: 'official',
        url: fred.sourceUrl,
        status: 'healthy',
        lastAttemptAt: retrievedAt,
        lastSuccessAt: retrievedAt,
        itemsUsed: 1,
        marketTags: ['global', 'united-states', 'fx'],
        publicMessage: 'Latest preview retrieval succeeded.',
      },
      {
        id: 'cbrt-usd-try',
        name: cbrt.sourceName,
        type: 'official',
        url: cbrt.sourceUrl,
        status: 'healthy',
        lastAttemptAt: retrievedAt,
        lastSuccessAt: retrievedAt,
        itemsUsed: 1,
        marketTags: ['turkey', 'fx'],
        publicMessage: 'Latest preview retrieval succeeded.',
      },
      {
        id: 'gdelt-global',
        name: 'GDELT Project',
        type: 'news',
        url: 'https://www.gdeltproject.org/',
        status: 'stale',
        lastAttemptAt: generatedAt,
        lastSuccessAt: isoFrom(now, -10),
        itemsUsed: 2,
        marketTags: ['global', 'news'],
        publicMessage: 'Last good discovery result retained.',
      },
      {
        id: 'fred-placeholder',
        name: 'FRED optional series',
        type: 'official',
        url: 'https://fred.stlouisfed.org/',
        status: 'unavailable',
        lastAttemptAt: generatedAt,
        lastSuccessAt: null,
        itemsUsed: 0,
        marketTags: ['global', 'united-states'],
        publicMessage: 'Optional source unavailable in this preview.',
      },
    ],
  };
}
