export const logLines = [
  "thought spawned: did i say that right",
  "context switch: conversation from 2019",
  "intrusive: what if",
  "stack overflow in: self-reference",
  "interrupt: phone buzzed (it didn't)",
  "memory leak detected in: unsent reply",
  "recursion depth exceeded: why-did-i",
  "reprioritizing: everything",
  "cache miss: what was i doing",
  "parse error: their tone",
  "retry: apology draft #47",
  "timeout: present moment",
  "race condition: two worries at once",
  "unhandled exception: weekend",
  "deadlock: explain vs. don't explain",
  "packet loss: last five minutes",
  "segfault in: small talk",
  "sync failed: mood ↔ face",
  "fetch failed: reason for doing this",
  "gc paused: cannot release",
  "stack trace: childhood → now → tomorrow",
  "warning: attention split across 9 threads",
  "spawn: what they thought of me",
  "kill signal ignored: rumination",
  "watchdog: mood dropped",
  "fd leak: open tabs (mental)",
  "dns failure: where am i",
  "handshake error: eye contact",
  "overrun: schedule collision",
  "backlog growing: unprocessed feelings",
  "heartbeat irregular",
  "rollback failed: the thing i said"
];
